# workflow to show how to develop workflows in branches
name: Develop in a branch
on: [pull_request, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - run: |
          echo "Workflow triggered in branch '${{ github.ref }}'"
          echo "Workflow triggered by event '${{ github.event }}'"
          echo "Workflow triggered by actor '${{ github.actor }}'"
          echo "PR title is '${{ github.event.pull_request.title }}'"
